defaults:
  -
    scope:
      path: "_slides" 
    values:
      layout: "iframe"

collections:
  slides:
    output: true
    
defaults:
   -
     scope:
       path: "_slides"  #__
     values:
       layout: "iframe"

 collections:
   slides:
     output: true
